#!/bin/zsh
#
# William Falk-Wallace
# osxrc
#

#################################  OSX HACKS  ##################################
### fix iterm2 session namespace quirk
alias subl="reattach-to-user-namespace subl"
### copy-paste in preview
alias qlpbon='defaults write com.apple.finder QLEnableTextSelection -bool TRUE; killall Finder'
alias qlpboff='defaults write com.apple.finder QLEnableTextSelection -bool FALSE; killall Finder'
### show hidden files
alias showhiddenon='defaults write com.apple.finder AppleShowAllFiles true; killall Finder'
alias showhiddenoff='defaults write com.apple.finder AppleShowAllFiles false; killall Finder'
### dashboard control
alias dashoff='defaults write com.apple.dashboard mcx-disabled -boolean YES; killall Dock'
alias dashon='defaults write com.apple.dashboard mcx-disabled -boolean NO; killall Dock'
### safari loading pie instead of bar
alias safaripieon='defaults write com.apple.Safari DebugUsePieProgressIndicator -bool true'
alias safaripieoff='defaults write com.apple.Safari DebugUsePieProgressIndicator -bool false'
### yosemite press and hold key repeat
alias keyrepeaton='defaults write -g ApplePressAndHoldEnabled -bool false'
alias keyrepeatoff='defaults write -g ApplePressAndHoldEnabled -bool true'

###################################  STATS  ####################################
### wifi info
alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'
alias wifi='airport -I' # TODO: Document flags
alias wifiscan='airport -s' # TODO: Document flags

#############################  OSX TERMINAL HACKS  #############################
### name the current terminal tab
# From thelucid.com/2012/01/04/naming-your-terminal-tabs-in-osx-lion
function name_tab()
{
  if [ $# -ne 1 ]; then
    echo "Usage: name_tab <name>"
  fi
  printf "\e]1;$1\a"
}
### name the current terminal window
function name_window()
{
  if [ $# -ne 1 ]; then
    echo "Usage: name_window <name>"
  fi
  printf "\e]2;$1\a"
}
### name the current terminal tab or window
function name()
{
  if [ $# -ne 2 ]; then
    echo "Usage: name <tab|t|window|win|w> <name>"
  fi
  case "$1" in
    "tab") name_tab $2 ;;
    "t") name_tab $2 ;;
    "window") name_window $2 ;;
    "win") name_window $2 ;;
    "w") name_window $2 ;;
    *) echo "Usage: name <tab|t|window|win|w> <name>" ;;
  esac
}
