#!/bin/zsh
#
# William Falk-Wallace
# zsh_config
#

#################################  VENV JUNK  ##################################
if [ -f "/usr/local/bin/virtualenvwrapper.sh" ]; then
  source /usr/local/bin/virtualenvwrapper.sh
  export WORKON_HOME="$HOME/.virtualenvs"
fi

##################################  NVM JUNK  ##################################
export NVM_DIR="/usr/local/opt/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

#################################  GOOG JUNK  ##################################
source /Users/wfalkwallace/google-cloud-sdk/completion.zsh.inc

