#!/bin/zsh
#
# William Falk-Wallace
# zsh_path
#

### standard path
PATH=$HOME/bin:$PATH
### add personal & third party scripts to path
PATH=$PATH:$HOME/code/scripts:$HOME/code/scripts/3P
### add homebrew
PATH=$HOME/homebrew/bin:$PATH #TODO: make this conditional

export PATH


