#!/bin/zsh
#
# William Falk-Wallace
# zsh_path
#

### standard path
PATH=$HOME/bin:$PATH
### add personal & third party scripts to path
PATH=$PATH:$HOME/code/bin

PATH=/usr/local/bin:/usr/local/sbin:$PATH
### add gcloud
source /Users/wfalkwallace/google-cloud-sdk/path.zsh.inc

export PATH

